/**
 * YAAM Stream - Export Formats Demo
 * Demonstrates all supported export formats
 */

const { YaamStream } = require('yaam-stream');
const fs = require('fs-extra');
const path = require('path');

async function exportDemo() {
  console.log('📊 YAAM Stream Export Formats Demo\n');

  // Comprehensive document data for testing all formats
  const documentData = {
    cover: {
      category: "Multi-Format Demo",
      title: "Export Formats Showcase",
      subtitle: "Testing all supported export formats",
      meta: [
        { label: "Date", value: new Date().toLocaleDateString() },
        { label: "Formats", value: "6 Export Types" },
        { label: "Demo", value: "YAAM Stream Features" }
      ]
    },
    sections: [
      {
        type: "content",
        title: "HTML Export",
        subtitle: "Responsive and Interactive",
        content: "HTML export creates fully responsive documents with interactive animations, smooth scrolling, and professional typography. The output includes CSS animations, JavaScript interactions, and is optimized for web viewing across all devices."
      },
      {
        type: "content",
        title: "PDF Export",
        subtitle: "Professional Document Format",
        content: "PDF export generates high-quality printable documents with professional formatting, custom headers and footers, page numbers, and optional encryption. Supports various page sizes and orientations with precise layout control."
      },
      {
        type: "content",
        title: "PowerPoint Export",
        subtitle: "Animated Presentations",
        content: "PowerPoint export creates dynamic presentations with slide transitions, animations, and professional templates. Each document section becomes a slide with appropriate formatting and visual enhancements."
      },
      {
        type: "content",
        title: "LaTeX Export",
        subtitle: "Academic Publishing",
        content: "LaTeX export produces publication-ready documents for academic and scientific use. Includes proper mathematical formatting, bibliography support, and professional typesetting suitable for journals and conferences."
      },
      {
        type: "content",
        title: "DOCX Export",
        subtitle: "Microsoft Word Compatibility",
        content: "DOCX export ensures compatibility with Microsoft Word and other word processors. Maintains formatting, styles, and document structure while allowing for further editing and collaboration."
      },
      {
        type: "content",
        title: "Markdown Export",
        subtitle: "Developer-Friendly Format",
        content: "Markdown export creates clean, readable text files in standard Markdown format. Perfect for version control, documentation systems, and developer workflows while maintaining content structure."
      },
      {
        type: "highlights",
        title: "Export Features",
        subtitle: "Capabilities by Format",
        items: [
          { icon: "🌐", title: "HTML", text: "Interactive, responsive, animated" },
          { icon: "📄", title: "PDF", text: "Printable, encrypted, professional" },
          { icon: "🎯", title: "PPTX", text: "Presentations, animations, slides" },
          { icon: "📚", title: "LaTeX", text: "Academic, mathematical, precise" },
          { icon: "📝", title: "DOCX", text: "Editable, compatible, structured" },
          { icon: "💻", title: "Markdown", text: "Developer-friendly, version control" }
        ]
      },
      {
        type: "table",
        title: "Format Comparison",
        subtitle: "Feature Matrix",
        headers: ["Format", "Interactive", "Printable", "Editable", "Animations", "File Size"],
        rows: [
          ["HTML", "Yes", "Limited", "Yes", "Yes", "Medium"],
          ["PDF", "No", "Yes", "Limited", "No", "Large"],
          ["PPTX", "Yes", "No", "Yes", "Yes", "Medium"],
          ["LaTeX", "No", "Yes", "Yes", "No", "Small"],
          ["DOCX", "Limited", "Yes", "Yes", "No", "Medium"],
          ["Markdown", "No", "No", "Yes", "No", "Small"]
        ]
      },
      {
        type: "signature",
        left: "Generated by YAAM Stream",
        right: "Multi-Format Export Demo"
      }
    ]
  };

  try {
    // Initialize YAAM Stream
    const yaam = new YaamStream({
      data: documentData,
      config: {
        theme: 'elegant',
        animation: {
          speed: 20,
          effects: {
            typewriter: true,
            fadeIn: true
          }
        },
        export: {
          quality: 'print',
          embedFonts: true,
          metadata: {
            title: "Export Formats Demo",
            author: "YAAM Stream",
            subject: "Multi-format export showcase"
          },
          pdf: {
            header: "YAAM Stream Export Demo",
            footer: "Page {page} of {total}",
            pageNumbers: true
          },
          pptx: {
            slideSize: {
              width: 10,
              height: 5.625
            },
            animations: true,
            transitions: true
          }
        }
      }
    });

    console.log('🎨 Generating base document...');
    
    // Generate the base HTML document
    const html = await yaam.generate();
    console.log('✅ Base document generated');
    console.log(`📊 HTML length: ${html.length.toLocaleString()} characters\n`);

    // Export to all supported formats
    console.log('🔄 Exporting to all supported formats...');
    const allFormats = ['html', 'pdf', 'pptx', 'latex', 'docx', 'markdown'];
    
    const results = await yaam.export(allFormats);
    
    console.log('✅ All exports completed!\n');
    
    // Display export results
    console.log('📁 Export Results:');
    console.log('=' .repeat(80));
    
    let totalSize = 0;
    results.forEach((result, index) => {
      const sizeKB = (result.size / 1024).toFixed(1);
      const sizeMB = (result.size / (1024 * 1024)).toFixed(2);
      totalSize += result.size;
      
      console.log(`${index + 1}. ${result.format.toUpperCase()}`);
      console.log(`   📄 File: ${result.filename}`);
      console.log(`   📏 Size: ${sizeKB} KB (${sizeMB} MB)`);
      console.log(`   📍 Path: ${result.path}`);
      console.log(`   ⭐ Quality: ${result.quality}`);
      
      if (result.pages) {
        console.log(`   📄 Pages: ${result.pages}`);
      }
      
      if (result.duration) {
        console.log(`   ⏱️  Duration: ${result.duration}ms`);
      }
      
      console.log('');
    });

    console.log('=' .repeat(80));
    console.log(`📊 Summary:`);
    console.log(`   🎯 Formats: ${results.length}`);
    console.log(`   💾 Total size: ${(totalSize / (1024 * 1024)).toFixed(2)} MB`);
    console.log(`   ⚡ Avg export time: ${(results.reduce((sum, r) => sum + (r.duration || 0), 0) / results.length).toFixed(0)}ms`);

    // Format-specific analysis
    console.log('\n🔍 Format Analysis:');
    
    const formatAnalysis = {
      html: {
        strengths: ['Interactive', 'Responsive', 'Animated'],
        useCases: ['Web publishing', 'Email reports', 'Interactive dashboards'],
        fileSize: results.find(r => r.format === 'html')?.size || 0
      },
      pdf: {
        strengths: ['Printable', 'Professional', 'Secure'],
        useCases: ['Business reports', 'Legal documents', 'Archival'],
        fileSize: results.find(r => r.format === 'pdf')?.size || 0
      },
      pptx: {
        strengths: ['Presentations', 'Animations', 'Slides'],
        useCases: ['Business presentations', 'Training materials', 'Sales decks'],
        fileSize: results.find(r => r.format === 'pptx')?.size || 0
      },
      latex: {
        strengths: ['Academic', 'Mathematical', 'Precise'],
        useCases: ['Research papers', 'Academic publications', 'Theses'],
        fileSize: results.find(r => r.format === 'latex')?.size || 0
      },
      docx: {
        strengths: ['Editable', 'Compatible', 'Structured'],
        useCases: ['Collaborative editing', 'Word processing', 'Documentation'],
        fileSize: results.find(r => r.format === 'docx')?.size || 0
      },
      markdown: {
        strengths: ['Developer-friendly', 'Version control', 'Lightweight'],
        useCases: ['Developer docs', 'Version control', 'Static sites'],
        fileSize: results.find(r => r.format === 'markdown')?.size || 0
      }
    };

    Object.entries(formatAnalysis).forEach(([format, analysis]) => {
      const result = results.find(r => r.format === format);
      if (result) {
        console.log(`\n${format.toUpperCase()} (${(result.size / 1024).toFixed(1)} KB):`);
        console.log(`   💪 Strengths: ${analysis.strengths.join(', ')}`);
        console.log(`   🎯 Use cases: ${analysis.useCases.join(', ')}`);
      }
    });

    // Performance comparison
    console.log('\n⚡ Performance Comparison:');
    const sortedBySize = [...results].sort((a, b) => a.size - b.size);
    const sortedByTime = [...results].filter(r => r.duration).sort((a, b) => a.duration! - b.duration!);

    console.log('\n📏 Smallest to Largest:');
    sortedBySize.forEach((result, index) => {
      const sizeKB = (result.size / 1024).toFixed(1);
      console.log(`   ${index + 1}. ${result.format.toUpperCase()}: ${sizeKB} KB`);
    });

    if (sortedByTime.length > 0) {
      console.log('\n⚡ Fastest to Slowest:');
      sortedByTime.forEach((result, index) => {
        console.log(`   ${index + 1}. ${result.format.toUpperCase()}: ${result.duration}ms`);
      });
    }

    // Save export report
    const exportReport = {
      timestamp: new Date().toISOString(),
      formats: results.length,
      totalSize: totalSize,
      results: results.map(r => ({
        format: r.format,
        filename: r.filename,
        size: r.size,
        duration: r.duration
      }))
    };

    await fs.writeJSON('export-report.json', exportReport, { spaces: 2 });
    console.log('\n📊 Export report saved to: export-report.json');

    // Cleanup
    await yaam.cleanup();
    console.log('\n🧹 Cleanup completed');
    console.log('\n✨ Export Demo completed successfully!');

  } catch (error) {
    console.error('❌ Export demo error:', error.message);
    
    // Provide helpful error messages
    if (error.message.includes('puppeteer')) {
      console.log('\n💡 PDF export requires Puppeteer. Install with:');
      console.log('   npm install puppeteer');
    }
    
    if (error.message.includes('canvas') || error.message.includes('sharp')) {
      console.log('\n💡 Some export features require additional dependencies.');
      console.log('   npm install canvas sharp');
    }
    
    process.exit(1);
  }
}

// Batch export helper function
async function batchExport(formats, options = {}) {
  const yaam = new YaamStream(options);
  
  try {
    console.log(`📦 Batch export to ${formats.length} formats...`);
    
    const results = await yaam.export(formats);
    
    console.log('✅ Batch export completed');
    return results;
    
  } finally {
    await yaam.cleanup();
  }
}

// Format-specific export helper
async function exportToFormat(format, options = {}) {
  const yaam = new YaamStream(options);
  
  try {
    console.log(`🎯 Exporting to ${format.toUpperCase()}...`);
    
    const [result] = await yaam.export([format]);
    
    console.log('✅ Export completed');
    console.log(`   📄 File: ${result.filename}`);
    console.log(`   📏 Size: ${(result.size / 1024).toFixed(1)} KB`);
    
    return result;
    
  } finally {
    await yaam.cleanup();
  }
}

// Run the demo
if (require.main === module) {
  console.log('🎯 YAAM Stream Export Formats Demo');
  console.log('=' .repeat(50));
  
  // Check for specific format argument
  const formatArg = process.argv.find(arg => 
    ['html', 'pdf', 'pptx', 'latex', 'docx', 'markdown'].includes(arg)
  );
  
  if (formatArg) {
    // Run single format export
    exportToFormat(formatArg, {
      data: documentData,
      config: {
        theme: 'elegant',
        export: { quality: 'print' }
      }
    }).catch(console.error);
  } else {
    // Run full demo
    exportDemo().catch(console.error);
  }
}

module.exports = { 
  exportDemo, 
  batchExport, 
  exportToFormat 
};